fix(NODE_PATH): KIT_NODE_PATH

diff --git a/root/bin/kit b/root/bin/kit
--- a/root/bin/kit
+++ b/root/bin/kit
@@ -13,11 +13,11 @@ KIT=$(cd "$(dirname $(readlink -f ${BASH_SOURCE[0]}))/.." &>/dev/null && pwd)
         pwd
     )"
 
-NODE_PATH="${NODE_PATH:=$($KIT/node_modules/.bin/pnpm node -p "process.execPath" 2>/dev/null || pnpm node -p "process.execPath" 2>/dev/null || node -p "process.execPath" 2>/dev/null)}"
-if ! command -v "$NODE_PATH" &> /dev/null; then
-    NODE_PATH=$(which node)
-    if [ -z "$NODE_PATH" ]; then
-        echo "Error: Node.js not found in PATH. Provide an NODE_PATH in your environment." >&2
+KIT_NODE_PATH="${KIT_NODE_PATH:=$($KIT/node_modules/.bin/pnpm node -p "process.execPath" 2>/dev/null || pnpm node -p "process.execPath" 2>/dev/null || node -p "process.execPath" 2>/dev/null)}"
+if ! command -v "$KIT_NODE_PATH" &> /dev/null; then
+    KIT_NODE_PATH=$(which node)
+    if [ -z "$KIT_NODE_PATH" ]; then
+        echo "Error: Node.js not found in PATH. Provide an KIT_NODE_PATH in your environment." >&2
         exit 1
     fi
 fi
@@ -31,7 +31,7 @@ KIT_TARGET="terminal" \
 KIT="$KIT" \
 KENV="$KENV" \
 NODE_NO_WARNINGS=1 \
-"$NODE_PATH" \
+"$KIT_NODE_PATH" \
 --loader "file://$KIT/build/loader.js" \
 "$KIT/run/terminal.js" \
 "$@"
diff --git a/root/script b/root/script
--- a/root/script
+++ b/root/script
@@ -2,15 +2,15 @@
 # ../../ of this script
 
 KIT=$(cd "$(dirname ${BASH_SOURCE[0]})" &> /dev/null && pwd)
-NODE_PATH="${NODE_PATH:=$($KIT/node_modules/.bin/pnpm node -p "process.execPath" 2>/dev/null || pnpm node -p "process.execPath" 2>/dev/null || node -p "process.execPath" 2>/dev/null)}"
+KIT_NODE_PATH="${KIT_NODE_PATH:=$($KIT/node_modules/.bin/pnpm node -p "process.execPath" 2>/dev/null || pnpm node -p "process.execPath" 2>/dev/null || node -p "process.execPath" 2>/dev/null)}"
 
-if [ -z "$NODE_PATH" ]; then
-    echo "Error: Node.js not found in PATH. Provide an NODE_PATH in your environment." >&2
+if [ -z "$KIT_NODE_PATH" ]; then
+    echo "Error: Node.js not found in PATH. Provide an KIT_NODE_PATH in your environment." >&2
     exit 1
 fi
 
 NODE_NO_WARNINGS=1 \
-"$NODE_PATH" \
+"$KIT_NODE_PATH" \
 --loader "file://$KIT/build/loader.js" \
 "$KIT/run/terminal.js" \
 "$@"
