fix(node): use NODE_PATH

diff --git a/root/script b/root/script
--- a/root/script
+++ b/root/script
@@ -2,15 +2,15 @@
 # ../../ of this script
 
 KIT=$(cd "$(dirname ${BASH_SOURCE[0]})" &> /dev/null && pwd)
-EXEC_PATH="${EXEC_PATH:=$($KIT/node_modules/.bin/pnpm node -p "process.execPath" 2>/dev/null || pnpm node -p "process.execPath" 2>/dev/null || node -p "process.execPath" 2>/dev/null)}"
+NODE_PATH="${NODE_PATH:=$($KIT/node_modules/.bin/pnpm node -p "process.execPath" 2>/dev/null || pnpm node -p "process.execPath" 2>/dev/null || node -p "process.execPath" 2>/dev/null)}"
 
-if [ -z "$EXEC_PATH" ]; then
-    echo "Error: Node.js not found in PATH. Provide an EXEC_PATH in your environment." >&2
+if [ -z "$NODE_PATH" ]; then
+    echo "Error: Node.js not found in PATH. Provide an NODE_PATH in your environment." >&2
     exit 1
 fi
 
 NODE_NO_WARNINGS=1 \
-"$EXEC_PATH" \
+"$NODE_PATH" \
 --loader "file://$KIT/build/loader.js" \
 "$KIT/run/terminal.js" \
 "$@"
